/*
 Ebis Tracking Object
 Copyright 2019 YRGLM Inc.
 @external Ebis
*/
(function(){function p(a,b){n.call(this,a,b);this.g()}function r(a,b,c){this.m=a;this.u=b;this.ja=c;this.k="cid pid o1id o2id o3id o4id o5id m1id a1id".split(" ")}function l(a,b){n.call(this,a,b);this.g()}function q(a,b){n.call(this,a,b);this.g()}function n(a,b){this.f=a;this.data=b}function s(){this.V={type:"ebisAccessTypes",other1:"ebisOther1",other2:"ebisOther2",other3:"ebisOther3",other4:"ebisOther4",other5:"ebisOther5",member_name:"ebisMember",amount:"ebisAmount",page_id:"ebisPageID",argument:"argument",
referrer:"referrer",pageurl:"pageurl",pagetitle:"pagetitle",user_agent:"ebisUA",tag_id:"tag_id",dn:"dn",js:"js",td:"td",lstd:"lstd",otd:"otd",xd:"xd",cid:"argument",pid:"ebisPageID",o1id:"ebisOther1",o2id:"ebisOther2",o3id:"ebisOther3",o4id:"ebisOther4",o5id:"ebisOther5",m1id:"ebisMember",a1id:"ebisAmount",rand:"ebisRand",pids:"pids",unmatched_flow_pids:"ebisUnmatchedFlowPids",ai:"fmai",cr:"cr",nw:"nw",mt:"mt",kw:"kw",gr:"gr",mid:"mid",device:"device",ss:"ss",cd:"cd"}}function u(a){return function(b){b=
a.exec(b);return null!==b?b[0].slice(b[0].indexOf("=")+1):""}}function d(a,b,c,e,g,d,k){this.n=b;this.v="https://ac.ebis.ne.jp/rec.php?ebisV=6.2";this.Jb=["click","pv","search"];this.Ia="pv,search";this.u=x;this.startTime=this.u.getTime();this.args=e||[];this.recRS=k||0;this.recQ=d||[];this.b=null;this.Kb=a||[];this.q=[];this.c={};this.S=2E3;this.qa=new s;this.La=c||[];this.Aa=20;this.a=[];this.R=[];this.d=null;this.frg=g||null;this.l=this.I=this.O=!1;this.A=null;this.h={log:this.log,getItem:function(a){try{return localStorage.getItem(a)}catch(b){return null}},
setItem:function(a,b){try{localStorage.setItem(a,b)}catch(c){}},removeItem:function(a){try{localStorage.removeItem(a)}catch(b){}}}}function h(){}var x=new Date,v={LOG:"2",SEO:"4"},t={SEARCH_FIX_CONTAIN:"1",SEARCH_NOT_CONTAIN:"2",SEARCH_FRONT:"3"},y=/^Mozilla\/5\.0 \(Macintosh; Intel Mac OS X (\d+_\d+_?\d*)\) AppleWebKit\/[\d\.]+ \(KHTML, like Gecko\) Version\/(\d+\.\d+\.?\d*) Safari\/.+$/,z=/^Mozilla\/5\.0 \((iPhone|iPad); CPU.+OS [\d_]+ like Mac OS X\) AppleWebKit\/[\d\.]+ \(KHTML, like Gecko\) Version\/(\d+\.\d+\.?\d*) Mobile\/.+ Safari\/.+$/;
h.prototype.ga=function(a,b){function c(a,b){var c=void 0!==a?a.split(","):[];void 0!==b&&Array.prototype.push.apply(c,b.split(","));c=c.filter(function(a,b,c){return c.indexOf(a)===b});return c.join(",")}for(var e in b)b.hasOwnProperty(e)&&(a[e]="type"===e?c(a[e],b[e]):b[e]);return a};h.prototype.Ea=function(a){return this.ga({},a)};h.prototype.Ma=function(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]="function"===typeof a[c]?a[c]:encodeURIComponent(a[c]));return b};h.prototype.ob=function(a){return Object.keys(a).map(function(b){return encodeURIComponent(b)+
"="+encodeURIComponent(a[b])}).join("&")};h.prototype.C=function(a){a=a.dataset;var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b};h.prototype.J=function(a,b){function c(){}c.prototype=b.prototype;a.Mb=b.prototype;a.prototype=new c};h.prototype.Va=function(a){return a.replace("http://","").replace("https://","").split(/[/?#]/)[0]};d.prototype.ba=function(){return document.domain};d.prototype.Wa=function(){return window.navigator.userAgent};d.prototype.Ra=function(){var a=this.ba(),b=
this.A.filter(function(b){return(b=b.e1)?RegExp("^.*"+b.replace(/\./g,"\\.")+"$").test(a):!1})[0];return b?{e:b.e1,host:"https://"+b.cn+"/rec.php?ebisV=6.2"}:null};d.prototype.init=function(a){this.b=a.argument;if(!this.b)throw Error("Argument not set");var b=window.ebis.cvx.cdl;b&&0<b.length&&this.nb(this.Wa())&&(this.A=b);b=null;if(a.tagHost)this.v=a.tagHost+"?ebisV=6.2";else if(this.A){var c=this.Ra();c&&(this.v=c.host,b=c.e,this.l=!0)}if(0<=this.args.indexOf(this.b))this.la(b);else{this.args.push(this.b);
this.la(b);this.q=this.Kb;this.a=this.Sa();this.R=this.Ta();b=this.Xa(this.b);b||(b={argument:this.b},this.Q(b));this.ra(b);this.M();if(this.n.W)try{"string"===typeof window.ebis.cvx.xdl&&(this.X=RegExp(window.ebis.cvx.xdl))}catch(e){}this.d=this.Ba();this.sa(a);this.ub();this.na();this.xb()}};d.prototype.Q=function(a){this.q.push(a)};d.prototype.push=function(a){this.Q(a);this.M()};d.prototype.la=function(a){var b=this.sb();this.c={referrer:document.referrer,pagetitle:document.title,pageurl:b,user_agent:window.navigator.userAgent};
a&&(this.c.cd=a);this.Ca();this.zb()};d.prototype.Ua=function(){return document.URL};d.prototype.sb=function(){var a=this.Ua(),b=a,c=null,e={},g=a.indexOf("#");if(-1!==g){for(var d=a.substr(g+1).split(/(?=[?&#])/),k=[],h=/(?:^|[?&#])(argument|ai|cr|nw|mt|kw|gr|mid|device|_ebcv)=(.*)/,l=0;l<d.length;l++){var m=d[l].match(h);m&&m[1]?"_ebcv"===m[1]?c=m[2]:e[m[1]]="argument"===m[1]&&e[m[1]]?e[m[1]]+(","+m[2]):m[2]:k.push(d[l])}if(null!==c||0<Object.keys(e).length)b=a.substr(0,g),0<k.length&&(b+="#"+k.join(""))}null===
this.frg&&(a={},a.cvflow_param=c,a.click_param=e,this.frg=a);return b};d.prototype.nb=function(a){var b=y.exec(a);if(b&&1<b.length){if(10.13>Number(b[1].split("_",2).join(".")))return!1;a=b[2]}else{a=z.exec(a);if(!a||3>a.length)return!1;a=a[2]}return 11<=parseInt(a)};d.prototype.Ca=function(){if(!0!==window.ebis.cvx.pvr)this.I=this.O=!1;else{this.O=!0;var a="_ebss_"+this.b;this.I=Boolean(this.$(a));this.P(a+"=1",(new Date((new Date).getTime()+18E5)).toUTCString())}};d.prototype.zb=function(){var a=
this.B(),b=this.rb();b&&(a&&a!=b&&(this.c.otd=a),a=b,this.l||this.pa(a));this.c.td=a};d.prototype.ra=function(a){if(null!==this.frg&&0!==Object.keys(this.frg.click_param).length){var b=this.frg.click_param;if(void 0!==b.argument&&-1!==b.argument.indexOf(a.argument)){for(var c in b)"argument"!==c&&(a[c]=b[c]);if(a.kw)try{a.kw=decodeURIComponent(a.kw)}catch(e){}}}};d.prototype.Eb=function(a,b){return b||this.Gb(a)||this.Fb(a)||this.Hb(a)};d.prototype.eb=function(a){var b=void 0!==a.cid;return(a=b?a.cid:
a.argument)?a===this.b||b&&0<=this.args.indexOf(a)?!0:!1:!1};d.prototype.Gb=function(a){return a.pids&&""!==a.pids||this.n.ia&&this.T(v.LOG)};d.prototype.Fb=function(a){return-1!==a.type.indexOf("click")};d.prototype.Hb=function(a){return-1!==a.type.indexOf("search")};d.prototype.Za=function(a){return(new Date).getTime()+"."+a};d.prototype.Ga=function(a,b){return this.qa.va(a,b)};d.prototype.cbo=function(a,b){var c=a.js?document.createElement("script"):new window.Image(1,1);a.callback&&"function"==
typeof a.callback&&(this.i=c,c.onload=c.onerror=c.onabort=a.callback,this.tmo=setTimeout(c.onload,this.S));c.src=this.Ga(a,b);var e=0===this.recRS&&!this.tmo;if(a.js){c.type="text/javascript";c.async=!0;var g=document.getElementsByTagName("script")[0];g.parentNode.insertBefore(c,g)}else e&&(c.onload=c.onerror=c.onabort=this.w);e&&(this.tmo=setTimeout(this.w,this.S))};d.prototype.w=function(a){var b=window.ebis;clearTimeout(b.tmo);if(void 0!==b.recQ){b.recRS=2;for(var c=0;c<b.recQ.length;c++){var e=
b.recQ[c];"string"==typeof a&&(e.ha.td=a);b.cbo(e.ha,e.host)}b.recQ.length=0}};d.prototype.cb=function(a){a.t?this.l||this.pa(a.t):(this.h.removeItem("_ebtd"),this.l||this.P("_ebtd=",(new Date((new Date).getTime()-1)).toUTCString()));this.w(this.c.td)};d.prototype.D=function(){return document.cookie};d.prototype.$=function(a){for(var b=this.D().split("; "),c=0;c<b.length;c++){var e=b[c].split("=");if(e[0]===a&&e[1])return e[1]}return null};d.prototype.B=function(){var a=this.$a();this.c.lstd=a?a.substring(a.indexOf(".")+
1):"";a=this.$("_ebtd")||a;if(!a)return"";var b=a.indexOf(".");if(!this.e){var c=a.substring(0,b);this.e=this.F()[c]}return a.substring(b+1)};d.prototype.$a=function(){return this.h.getItem("_ebtd")};d.prototype.Sa=function(){for(var a=this.D().split("; "),b="_ebcv_"+this.b,c="",e=0;e<a.length;e++){var g=a[e].split("=");if(g[0]===b&&void 0!==g[1]){c=g[1];break}}""===c&&(a=this.h.getItem(b))&&(c=a);a=[];c=c.split(",");for(b=0;b<c.length;b++)e=c[b].split("."),this.fa(e[0],e[1])&&!this.jb(e[2])&&a.push({pid:e[0],
oid:e[1],expires:e[2]});return a};d.prototype.jb=function(a){return a?(a=parseInt(a,36))?0<parseInt((new Date).getTime()/100)-a:!0:!0};d.prototype.Ta=function(){var a=[],b;if(this.frg&&this.frg.cvflow_param)b=this.frg.cvflow_param;else return a;b=b.split(",");for(var c=0;c<b.length;c++){var e=b[c].split(".");e[0]===this.b&&this.fa(e[1],e[2])&&a.push({pid:e[1],oid:e[2]})}return a};d.prototype.G=function(a,b){if(!a)return null;for(var c=0;c<a.length;c++)if(a[c].pid===b)return c;return null};d.prototype.fa=
function(a,b){return void 0===a||null===a||""===a||!a.match(/^[0-9a-zA-Z_-]+$/)||void 0===b||null===b||""===b||0>=b?!1:null===(b+"").match(/^\d+$/)?!1:!0};d.prototype.na=function(){var a="_ebcv_"+this.b,b=a+"=",c,e=null;if(0<this.a.length){e=[];c=parseInt((new Date).getTime()-1);for(var g=0;g<this.a.length;g++){e.push(this.a[g].pid+"."+this.a[g].oid+"."+this.a[g].expires);var d=100*parseInt(this.a[g].expires,36);d>c&&(c=d)}e=e.join(",");b+=e;c=(new Date(c)).toUTCString()}else c=(new Date((new Date).getTime()-
1)).toUTCString(),b+="remove_cookie";this.P(b,c);e?this.h.setItem(a,e):this.h.removeItem(a)};d.prototype.P=function(a,b){for(var c=this.F(),e=1;e<c.length&&!this.ma(a,c[e],b);e++);};d.prototype.ma=function(a,b,c){document.cookie=a+"; path=/ ; expires="+c+"; domain="+b;b=this.D().split("; ");for(c=0;c<b.length;c++)if(b[c]===a)return!0;return!1};d.prototype.F=function(){for(var a=[],b=this.ba(),c=b.length;-1!==c;)c=b.lastIndexOf(".",c-1),a.push(b.substring(c+1));return a};d.prototype.Db=function(a){this.h.setItem("_ebtd",
a)};d.prototype.pa=function(a){for(var b=(new Date((new Date).getTime()+63072E6)).toUTCString(),c=this.F(),e=1;e<c.length+1;e++){var g=e+"."+a;if(this.ma("_ebtd="+g,c[e],b)){this.c.td=a;this.e=c[e];this.Db(g);break}}};d.prototype.oa=function(a){if(/[?&]_ebx=/.test(a))return!1;this.s=this.B();return this.s&&this.e?(a=(a=a.match(/^https?:\/\/([^\/?#]+)/i))&&a[1])&&-1<a.indexOf(this.e)||!this.X?!1:this.X.test(a):!1};d.prototype.link=function(a){return(this.s=this.B())?this.L(a):a};d.prototype.Z=function(){return this.s+
"."+parseInt((new Date).getTime()/100).toString(36)};d.prototype.L=function(a){var b={};b._ebx=this.Z();return this.qa.ta(a,b)};d.prototype.rb=function(){var a=/[?&]_ebx=([^&#]+)/.exec(document.URL);if(null===a)return null;a=a[1];try{var b=a.lastIndexOf("."),c=parseInt(a.substring(b+1),36)}catch(e){return null}return!c||1200<parseInt((new Date).getTime()/100)-c?null:a.substring(0,b)};d.prototype.Da=function(a,b){a=decodeURIComponent(a);for(var c=a.split(","),e=[],g=0;g<c.length;g++)0<=b.indexOf(c[g])&&
e.push(c[g]);return e.join(",")};d.prototype.Na=function(a){a=h.prototype.Ea(a);a.type=this.Da(a.type,this.Jb);a.type&&(a.js="cb",1===this.recRS?this.recQ.push({ha:a,host:this.v}):(this.cbo(a,this.v),0===this.recRS&&(this.recRS=1)))};d.prototype.M=function(){for(var a=[],b=this.a.length,c=0;c<this.q.length;c++){var e=this.q[c],g;a:{g=e;var d=void 0;for(d in g)if(g.hasOwnProperty(d)&&"argument"!==d){g=!0;break a}g=!1}d=!1;if(this.eb(e)){var k=this.tb(e,c);this.Eb(k,g)&&(this.Na(k),d=!0)}d||g&&a.push(e)}b!==
this.a.length&&this.na();this.q=a};d.prototype.tb=function(a,b){var c=this.fb(a,b),e=this.bb(a);if(this.n.ia&&this.n.Ha&&!e)try{c.pids=this.ya(decodeURIComponent(this.c.pageurl))}catch(g){}var e=this.Ya(c),d=this.ab(e);null!==d&&0<d.length&&(c.unmatched_flow_pids=d.join(","));this.vb(e,d);return c};d.prototype.Ya=function(a){var b=[];void 0!==a.pids&&""!==a.pids&&(b=a.pids.split(","));if(a.page_id)try{b=b.concat(decodeURIComponent(a.page_id).split(","))}catch(c){}if(a.pid)try{b=b.concat(decodeURIComponent(a.pid).split(","))}catch(e){}return b};
d.prototype.ab=function(a){if(0===a.length)return null;var b=[];try{"undefined"!==typeof window.ebis.cvx.rrl&&Array.isArray(window.ebis.cvx.rrl)&&(b=window.ebis.cvx.rrl)}catch(c){}if(0===b.length)return null;for(var e=[],d=0;d<b.length;d++)if(-1!==a.indexOf(b[d].pid)){var f=function(a){return a.pid===b[d].pid&&0===a.oid-1};("f"===b[d].uf&&0===this.a.filter(f).length||"t"===b[d].uf&&0===this.R.filter(f).length)&&e.push(b[d].pid)}return e};d.prototype.vb=function(a,b){if(a&&0!==a.length){var c=a;b&&
0<b.length&&(c=a.filter(function(a){return-1===b.indexOf(a)}));for(var e=0;e<c.length;e++){var d=this.G(this.a,c[e]);null!==d&&this.a.splice(d,1)}}};d.prototype.bb=function(a){return null!=a.page_id||null!=a.pid&&""!=a.pid};d.prototype.hb=function(a){return-1!==a.indexOf("_adp_u=a")};d.prototype.Pa=u(/[?&]_adp_p_ad=\d+/);d.prototype.Qa=u(/[?&]_adp_p_kw=\d+/);d.prototype.Oa=function(){var a=this.H();if(this.hb(a))return"";var b=this.Pa(a);if(""!==b)return"[adp_ad]"+b;a=this.Qa(a);return""!==a?"[adp_kw]"+
a:""};d.prototype.fb=function(a,b){var c=h.prototype.ga(a,this.c);c.type=void 0===c.type?this.Ia:c.type.replace(/click,?/g,"");var e=!1;if(this.ib(c))e=!0;else{var d=this.Oa();""!==d&&(c.ai=d,e=!0)}e&&(c.type+=",click");d=this.pb(c);if(e||!d)c.type=c.type.replace(/search,?/g,"");this.O&&(c.ss=this.I?"0":"1");c.rand=this.Za(b);return c=h.prototype.Ma(c)};d.prototype.gb=function(){return/[?&][dr]mai=([^&#])+/.test(this.H())};d.prototype.ib=function(a){return void 0!==a.cid?!1:a.ai?!0:this.gb()};d.prototype.pb=
function(a){return this.T(v.SEO)&&this.qb(a)};d.prototype.T=function(a){var b="";try{void 0!==typeof window.ebis.cvx.cf.ct&&(b=window.ebis.cvx.cf.ct.toString())}catch(c){}return-1!==b.indexOf(a)};d.prototype.qb=function(a){return this.mb(a)&&!this.kb()&&!this.lb()};d.prototype.mb=function(a){if(0<a.referrer.length){var b=a.referrer;try{b=decodeURIComponent(a.referrer)}catch(c){}return h.prototype.Va(b)!==location.hostname}return!1};d.prototype.H=function(){return location.search};d.prototype.kb=function(){return/[?&]trflg=/.test(this.H())};
d.prototype.lb=function(){return this.frg?this.frg.click_param.argument?!0:!1:!1};d.prototype.Xa=function(a){for(var b=0;b<this.q.length;b++)if(this.q[b].argument===a)return this.q[b];return null};d.prototype.log=function(a,b){b?console.log("EbisDebug: ",a,b):console.log("EbisDebug: ",a)};d.prototype.sa=function(a){var b=function(a,e,d){return function(){if("interactive"!==document.readyState&&"complete"!==document.readyState)setTimeout(b,this.Aa);else for(var f=0;f<d.length;f++)("EbisLinker"!==d[f]||
w.W||null!==a.d&&0!==a.d.length)&&new d[f](a,e)}}(this,a,this.La);b()};d.prototype.ya=function(a){var b=[],c=[];try{"undefined"!==typeof window.ebis.cvx.cvrl&&Array.isArray(window.ebis.cvx.cvrl)&&(c=window.ebis.cvx.cvrl)}catch(e){}if(!a)return!1;for(var d=0;d<c.length;d++)for(var f=c[d].cvr||[],k=c[d].pid,h=0;h<f.length;h++)if(this.ea(a,f[h],c[d].mt)){-1===b.indexOf(k)&&b.push(k);break}return b.join(",")};d.prototype.U=function(a,b){if(!a)return!1;try{a=decodeURIComponent(a)}catch(c){}for(var e=0;e<
b.length;e++)for(var d=b[e].rr,f=0;f<d.length;f++)if(this.ea(a,d[f],b[e].mt))return!0;return!1};d.prototype.ea=function(a,b,c){switch(c){case t.SEARCH_FIX_CONTAIN:return a===b;case t.SEARCH_NOT_CONTAIN:return-1===a.indexOf(b);case t.SEARCH_FRONT:return 0===a.indexOf(b);default:return-1!==a.indexOf(b)}};d.prototype.Ba=function(){var a,b=[],c=[];try{var e=parseInt(((new Date).getTime()+864E5*window.ebis.cvx.ed)/100).toString(36);"undefined"!==typeof window.ebis.cvx.rrl&&Array.isArray(window.ebis.cvx.rrl)&&
(c=window.ebis.cvx.rrl)}catch(d){}if(0===c.length)return null;for(var f=0;f<c.length;f++){if("t"===c[f].uf){var k=this.aa(this.R,c[f].pid,c[f].rrlp);null!==k&&b.push(this.b+"."+c[f].pid+"."+k)}else k=this.aa(this.a,c[f].pid,c[f].rrlp),null!==k&&(a=this.G(this.a,c[f].pid),null!==a&&this.a.splice(a,1),this.a.push({pid:c[f].pid,oid:k,expires:e}));a=c[f].rrlp.length-1;void 0!==typeof c[f].rrlp[a]&&this.U(this.c.pageurl,c[f].rrlp[a])&&("t"===c[f].uf?b.push(this.b+"."+c[f].pid+"."+c[f].rrlp.length):(a=
this.G(this.a,c[f].pid),null!==a&&this.a.splice(a,1),this.a.push({pid:c[f].pid,oid:c[f].rrlp.length,expires:e})))}return b};d.prototype.aa=function(a,b,c){if(""===a||0===a.length)return null;a=a.filter(function(a){return a.pid===b&&0<a.oid-1});if(""===a||0===a.length)return null;a=a[0].oid;return void 0!==typeof c[a-2]&&this.U(this.c.pageurl,c[a-2])?a-1:null};d.prototype.xb=function(){if(this.c.pageurl!==document.URL){var a=this.c.pageurl;-1===a.indexOf("#")&&(a+="#");location.replace(a)}};d.prototype.ub=
function(){if(!(60>=this.a.length)){var a=this.a.map(function(a,c){return{index:c,value:a}});a.sort(function(a,c){var e=parseInt(a.value.expires,36),d=parseInt(c.value.expires,36);return e<d?-1:e>d?1:a.index<c.index?-1:1});this.a=a.map(function(a){return a.value}).splice(-60)}};d.prototype.ca=function(a){return document.getElementsByClassName(a)};s.prototype.Fa=function(a){return this.V[a]?this.V[a]:""};s.prototype.va=function(a,b){var c="",e=[],d=!1;b.match(/\?/)&&(d=!0);for(var f in a)if(a.hasOwnProperty(f)){var k=
this.Fa(f);0<k.length&&0>e.indexOf(k)&&(d?c+="&":(c+="?",d=!0),e.push(k),c+=k+"="+a[f])}return b+c};s.prototype.ta=function(a,b){var c="",e=a,d=a.indexOf("#");-1!=d&&(c=a.substring(d+1),e=a.substring(0,d));var d=-1===e.indexOf("?")?"?":"&",f=h.prototype.ob(b);return e+d+f+(c?"#"+c:"")};n.prototype.g=function(){};h.prototype.J(q,n);q.prototype.g=function(){this.event="click";this.tagName=this.data.wa?this.data.wa:"ebis_button_trigger";var a=this.xa();this.yb(a);this.f.Lb=function(a,c,e,d,f,k,h,l,m,
n){window.ebis.push({type:"pv",argument:c,page_id:e,member_name:d||"",amount:n||"",other1:f||"",other2:k||"",other3:h||"",other4:l||"",other5:m||"",callback:function(){a.href&&(location.href=a.href)}});return!1}};q.prototype.xa=function(){for(var a=[],b=this.f.ca(this.tagName),c=0;c<b.length;c++){var e=h.prototype.C(b[c]),d;for(d in e)e.hasOwnProperty(d)&&e[d]==this.data.argument&&a.push(b[c])}return a};q.prototype.yb=function(a){function b(a){var b=h.prototype.C(this);b.type||(b.type="pv");this.target&&
"_blank"==this.target.toLowerCase()||(a.preventDefault(),b.callback=function(a,b){return function(){var a=window.ebis;clearTimeout(a.tmo);a.i&&a.i.onload&&(a.i.onload=a.i.onerror=a.i.onabort=null);location.href=b.href}}(b,this));window.ebis.push(b)}for(var c=0;c<a.length;c++)a[c].addEventListener(this.event,b,!1)};h.prototype.J(l,n);l.prototype.g=function(){this.event="scroll";this.K=!1;this.p=[];this.r=[];if(this.za())this.Cb();else return null;this.o=[];this.da=1;this.j={};this.ua();var a=this.ka();
this.Y(a);return this};l.prototype.Ka="ebis_tag_trigger";l.prototype.Cb=function(){for(var a=this.data.ja||"o1id",b=0;b<this.p.length;b++)this.r.push(new r(this.p[b],this.f.u,a))};l.prototype.za=function(){for(var a=this.f.ca(this.Ka),b=0;b<a.length;b++){var c=h.prototype.C(a[b]),e;for(e in c)c.hasOwnProperty(e)&&c[e]==this.data.argument&&this.p.push(a[b])}return 1<=this.p.length};l.prototype.Ib=function(){var a=[];this.K=!1;for(var b in this.r)if(this.r.hasOwnProperty(b)){var c=this.r[b];if(!c.N("isAdded")){var e=
c.position()-window.innerHeight;window.pageYOffset>=e?a.push(c.Ja()):this.K=!0}}return a};l.prototype.ka=function(){var a=this.Ib();this.K||this.wb();return a};l.prototype.Y=function(a){if(0<a.length){for(var b=0;b<a.length;b++)window.ebis.Q(a[b]);window.ebis.M()}};l.prototype.ua=function(){var a=function(a){return function(){var c=a.ka();a.Y(c)}}(this);window.addEventListener(this.event,a,!1);this.o[this.da]={element:window,event:this.event,j:a,capture:!1};this.da++};l.prototype.wb=function(){if(this.j in
this.o){var a=this.o[this.j];a.element.removeEventListener(a.event,a.j,a.capture);delete this.o[this.j]}};r.prototype.N=function(a,b){if(b)return this.m.dataset[a]=b,!0;var c=this.m.dataset,e;for(e in c)if(c.hasOwnProperty(e)&&e==a)return this.m.dataset[a];return""};r.prototype.position=function(){return this.m.offsetTop};r.prototype.Ja=function(){var a={type:"pv"};this.N("isAdded",!0);for(var b in this.k)if(this.k.hasOwnProperty(b)){var c;c=this.k[b]==this.ja?Math.round((new Date-this.u)/100)/10:
this.N(this.k[b]);a[this.k[b]]=c}return a};h.prototype.J(p,n);p.prototype.g=function(){this.Bb(this.f);this.Ab(this.f)};p.prototype.Bb=function(a){document.addEventListener("click",function(b){var c=window.ebis,e={};b=b.target;for(var d=100;b&&0<d;d--){if(b.href&&b.nodeName.match(/^a(?:rea)?$/i)){e=b;break}b=b.parentNode}if("http:"==e.protocol||"https:"==e.protocol)c.oa(e.href)&&(c=c.L(e.href))&&(e.href=c),a.d&&0<a.d.length&&(-1!==e.href.indexOf("_ebcv")?(c=RegExp("[&#]_ebcv=([^&#]*)","g"),b=c.exec(e.href),
e.href=e.href.replace(c,b[0]+","+a.d.join(","))):e.href=-1===e.href.indexOf("#")?e.href+"#_ebcv="+a.d.join(","):e.href+"&_ebcv="+a.d.join(","))},!1)};p.prototype.Ab=function(a){document.addEventListener("submit",function(b){var c=window.ebis;if((b=b.target)&&b.action){if(c.oa(b.action))if("get"===b.method.toLowerCase()){var d=document.createElement("input");d.type="hidden";d.name="_ebx";d.value=c.Z();b.appendChild(d)}else"post"===b.method.toLowerCase()&&(c=c.L(b.action))&&(b.action=c);a.d&&0<a.d.length&&
(-1!==b.action.indexOf("_ebcv")?(c=RegExp("[&#]_ebcv=([^&#]*)","g"),d=c.exec(b.action),b.action=b.action.replace(c,d[0]+","+a.d.join(","))):b.action=-1===b.action.indexOf("#")?b.action+"#_ebcv="+a.d.join(","):b.action+"&_ebcv="+a.d.join(","))}},!1)};var w={ia:!0,W:!0,Ha:!0};window.ebis=new d(window.ebis.q||window.ebis,w,[q,l,p],window.ebis.args,window.ebis.frg,window.ebis.recQ,window.ebis.recRS)})();
window.ebis.cvx={"cvrl":[],"rrl":[],"xdl":"phiten-store.com|phiten.com|phiten-runninglife.com|phiten-golf.com|phiten-upg.com|phiten-sleep.com","ed":"90","cf":{"ct":"1245"},"pvr":false,"cdl":[{"e1":"phiten-store.com","cn":"adebis.phiten-store.com"}]}